### ISSUE TITLE
Offset/Calibration post fetch

### ISSUE THREAD

**Issue by mindtripper** [Limych/ha-jq300#17]
It would be good to be able to manually "calibrate"/offset the data received from the device/cloud.
For instance; I have multiple sensors from other vendors that measure humidity. They are fairly accurate and provide data within ~1% margin of each other. The jq-300 however measures about 10 percentage points higher constantly.

If I change the calibration related to humidity in the PerThings app, it reverts back to the device detected value that is about 10 percentage points higher after a couple of minutes.
```

jq300:
  username: YOUR_EMAIL
  password: YOUR_PASSWORD
  devices:
    - Kitchen
      humidity_offset: -10
      .....

```

I do understand that this kind of offset is not very precise, but it's not going to be worse that the actual data reported by the device.
