### ISSUE TITLE
Integration fails when starting HA

### ISSUE THREAD

**Issue by remyderuysscher** [Limych/ha-jq300#3]
**Version of the custom_component**

Installed: 67c6161

**Configuration**
```yaml
jq300:
  username: !secret email_user
  password: !secret jq300_password
```

**Describe the bug**

After upgrading from the HACS store the integrations fails.

**Debug log**

```text

2020-05-17 13:16:48 ERROR (MainThread) [pyhaversion] Timeout error fetching version information from PyPi, 

```
